export interface TeamSummary {
  id: number
  name: string
  name_ko: string
  country_code: string
  appearances: number
  titles: number[]
  runner_ups: number[]
}

export const TEAMS: TeamSummary[] = [
  // ── 유럽 (100번대) ────────────────────────────────────────────────
  { id: 101, name: 'Germany',          name_ko: '독일',    country_code: 'GER', appearances: 20, titles: [1954,1974,1990,2014],      runner_ups: [1966,1982,1986,2002] },
  { id: 102, name: 'Italy',            name_ko: '이탈리아',               country_code: 'ITA', appearances: 18, titles: [1934,1938,1982,2006],      runner_ups: [1970,1994] },
  { id: 103, name: 'France',           name_ko: '프랑스',                 country_code: 'FRA', appearances: 16, titles: [1998,2018],                runner_ups: [2006,2022] },
  { id: 104, name: 'England',          name_ko: '잉글랜드',               country_code: 'ENG', appearances: 16, titles: [1966],                     runner_ups: [] },
  { id: 105, name: 'Spain',            name_ko: '스페인',                 country_code: 'ESP', appearances: 16, titles: [2010],                     runner_ups: [] },
  { id: 106, name: 'Netherlands',      name_ko: '네덜란드',               country_code: 'NED', appearances: 11, titles: [],                         runner_ups: [1974,1978,2010] },
  { id: 107, name: 'Croatia',          name_ko: '크로아티아',             country_code: 'CRO', appearances: 6,  titles: [],                         runner_ups: [2018] },
  { id: 108, name: 'Sweden',           name_ko: '스웨덴',                 country_code: 'SWE', appearances: 12, titles: [],                         runner_ups: [1958] },
  { id: 109, name: 'Hungary',          name_ko: '헝가리',                 country_code: 'HUN', appearances: 9,  titles: [],                         runner_ups: [1938,1954] },
  { id: 112, name: 'Russia',           name_ko: '러시아',     country_code: 'RUS', appearances: 11,  titles: [],                         runner_ups: [] },
  { id: 113, name: 'Portugal',         name_ko: '포르투갈',               country_code: 'POR', appearances: 8,  titles: [],                         runner_ups: [] },
  { id: 114, name: 'Belgium',          name_ko: '벨기에',                 country_code: 'BEL', appearances: 14, titles: [],                         runner_ups: [] },
  { id: 115, name: 'Poland',           name_ko: '폴란드',                 country_code: 'POL', appearances: 9,  titles: [],                         runner_ups: [] },
  { id: 116, name: 'Switzerland',      name_ko: '스위스',                 country_code: 'SUI', appearances: 12, titles: [],                         runner_ups: [] },
  { id: 117, name: 'Denmark',          name_ko: '덴마크',                 country_code: 'DEN', appearances: 6,  titles: [],                         runner_ups: [] },
  { id: 118, name: 'Austria',          name_ko: '오스트리아',             country_code: 'AUT', appearances: 7,  titles: [],                         runner_ups: [] },
  { id: 119, name: 'Czech Republic',   name_ko: '체코',                   country_code: 'CZE', appearances: 9,  titles: [],                         runner_ups: [] },
  { id: 120, name: 'Romania',          name_ko: '루마니아',               country_code: 'ROU', appearances: 7,  titles: [],                         runner_ups: [] },
  { id: 121, name: 'Serbia',           name_ko: '세르비아',               country_code: 'SRB', appearances: 13,  titles: [],                         runner_ups: [] },
  { id: 122, name: 'Greece',           name_ko: '그리스',                 country_code: 'GRE', appearances: 3,  titles: [],                         runner_ups: [] },
  { id: 123, name: 'Bulgaria',         name_ko: '불가리아',               country_code: 'BUL', appearances: 7,  titles: [],                         runner_ups: [] },
  { id: 124, name: 'Scotland',         name_ko: '스코틀랜드',             country_code: 'SCO', appearances: 8,  titles: [],                         runner_ups: [] },
  { id: 125, name: 'Wales',            name_ko: '웨일스',                 country_code: 'WAL', appearances: 2,  titles: [],                         runner_ups: [] },
  { id: 126, name: 'Northern Ireland', name_ko: '북아일랜드',             country_code: 'NIR', appearances: 3,  titles: [],                         runner_ups: [] },
  { id: 127, name: 'Republic of Ireland', name_ko: '아일랜드',            country_code: 'IRL', appearances: 3,  titles: [],                         runner_ups: [] },
  { id: 128, name: 'Norway',           name_ko: '노르웨이',               country_code: 'NOR', appearances: 3,  titles: [],                         runner_ups: [] },
  { id: 129, name: 'Iceland',          name_ko: '아이슬란드',             country_code: 'ISL', appearances: 1,  titles: [],                         runner_ups: [] },
  { id: 130, name: 'Slovakia',         name_ko: '슬로바키아',             country_code: 'SVK', appearances: 1,  titles: [],                         runner_ups: [] },
  { id: 131, name: 'Slovenia',         name_ko: '슬로베니아',             country_code: 'SLO', appearances: 2,  titles: [],                         runner_ups: [] },
  { id: 132, name: 'Bosnia & Herzegovina', name_ko: '보스니아',           country_code: 'BIH', appearances: 1,  titles: [],                         runner_ups: [] },
  { id: 133, name: 'Ukraine',          name_ko: '우크라이나',             country_code: 'UKR', appearances: 1,  titles: [],                         runner_ups: [] },
  { id: 134, name: 'Albania',          name_ko: '알바니아',               country_code: 'ALB', appearances: 0,  titles: [],                         runner_ups: [] },
  { id: 135, name: 'North Macedonia',  name_ko: '북마케도니아',           country_code: 'MKD', appearances: 0,  titles: [],                         runner_ups: [] },
  { id: 136, name: 'Montenegro',       name_ko: '몬테네그로',             country_code: 'MNE', appearances: 0,  titles: [],                         runner_ups: [] },
  { id: 137, name: 'Georgia',          name_ko: '조지아',                 country_code: 'GEO', appearances: 0,  titles: [],                         runner_ups: [] },
  { id: 138, name: 'Armenia',          name_ko: '아르메니아',             country_code: 'ARM', appearances: 0,  titles: [],                         runner_ups: [] },
  { id: 139, name: 'Azerbaijan',       name_ko: '아제르바이잔',           country_code: 'AZE', appearances: 0,  titles: [],                         runner_ups: [] },
  { id: 140, name: 'Belarus',          name_ko: '벨라루스',               country_code: 'BLR', appearances: 0,  titles: [],                         runner_ups: [] },
  { id: 141, name: 'Moldova',          name_ko: '몰도바',                 country_code: 'MDA', appearances: 0,  titles: [],                         runner_ups: [] },
  { id: 142, name: 'Cyprus',           name_ko: '키프로스',               country_code: 'CYP', appearances: 0,  titles: [],                         runner_ups: [] },
  { id: 143, name: 'Lithuania',        name_ko: '리투아니아',             country_code: 'LTU', appearances: 0,  titles: [],                         runner_ups: [] },
  { id: 144, name: 'Latvia',           name_ko: '라트비아',               country_code: 'LVA', appearances: 0,  titles: [],                         runner_ups: [] },
  { id: 145, name: 'Estonia',          name_ko: '에스토니아',             country_code: 'EST', appearances: 0,  titles: [],                         runner_ups: [] },
  { id: 146, name: 'Finland',          name_ko: '핀란드',                 country_code: 'FIN', appearances: 0,  titles: [],                         runner_ups: [] },

  // ── 남미 (200번대) ────────────────────────────────────────────────
  { id: 201, name: 'Brazil',           name_ko: '브라질',                 country_code: 'BRA', appearances: 22, titles: [1958,1962,1970,1994,2002], runner_ups: [] },
  { id: 202, name: 'Argentina',        name_ko: '아르헨티나',             country_code: 'ARG', appearances: 18, titles: [1978,1986,2022],           runner_ups: [1930,1990,2014] },
  { id: 203, name: 'Uruguay',          name_ko: '우루과이',               country_code: 'URU', appearances: 14, titles: [1930,1950],                runner_ups: [] },
  { id: 204, name: 'Chile',            name_ko: '칠레',                   country_code: 'CHI', appearances: 9,  titles: [],                         runner_ups: [] },
  { id: 205, name: 'Colombia',         name_ko: '콜롬비아',               country_code: 'COL', appearances: 6,  titles: [],                         runner_ups: [] },
  { id: 206, name: 'Ecuador',          name_ko: '에콰도르',               country_code: 'ECU', appearances: 4,  titles: [],                         runner_ups: [] },
  { id: 207, name: 'Paraguay',         name_ko: '파라과이',               country_code: 'PAR', appearances: 0,  titles: [],                         runner_ups: [] },
  { id: 208, name: 'Bolivia',          name_ko: '볼리비아',               country_code: 'BOL', appearances: 3,  titles: [],                         runner_ups: [] },
  { id: 209, name: 'Peru',             name_ko: '페루',                   country_code: 'PER', appearances: 5,  titles: [],                         runner_ups: [] },
  { id: 210, name: 'Venezuela',        name_ko: '베네수엘라',             country_code: 'VEN', appearances: 0,  titles: [],                         runner_ups: [] },

  // ── 북중미 (300번대) ──────────────────────────────────────────────
  { id: 301, name: 'Mexico',           name_ko: '멕시코',                 country_code: 'MEX', appearances: 17, titles: [],                         runner_ups: [] },
  { id: 302, name: 'USA',              name_ko: '미국',                   country_code: 'USA', appearances: 11, titles: [],                         runner_ups: [] },
  { id: 303, name: 'Canada',           name_ko: '캐나다',                 country_code: 'CAN', appearances: 2,  titles: [],                         runner_ups: [] },
  { id: 304, name: 'Costa Rica',       name_ko: '코스타리카',             country_code: 'CRC', appearances: 6,  titles: [],                         runner_ups: [] },
  { id: 305, name: 'Honduras',         name_ko: '온두라스',               country_code: 'HON', appearances: 3,  titles: [],                         runner_ups: [] },
  { id: 306, name: 'Panama',           name_ko: '파나마',                 country_code: 'PAN', appearances: 1,  titles: [],                         runner_ups: [] },
  { id: 307, name: 'Trinidad & Tobago', name_ko: '트리니다드 토바고',     country_code: 'TRI', appearances: 1,  titles: [],                         runner_ups: [] },
  { id: 308, name: 'Jamaica',          name_ko: '자메이카',               country_code: 'JAM', appearances: 1,  titles: [],                         runner_ups: [] },
  { id: 309, name: 'Haiti',            name_ko: '아이티',                 country_code: 'HAI', appearances: 1,  titles: [],                         runner_ups: [] },
  { id: 310, name: 'El Salvador',      name_ko: '엘살바도르',             country_code: 'ESA', appearances: 2,  titles: [],                         runner_ups: [] },
  { id: 311, name: 'Cuba',             name_ko: '쿠바',                   country_code: 'CUB', appearances: 1,  titles: [],                         runner_ups: [] },

  // ── 아프리카 (400번대) ────────────────────────────────────────────
  { id: 401, name: 'Morocco',          name_ko: '모로코',                 country_code: 'MOR', appearances: 6,  titles: [],                         runner_ups: [] },
  { id: 402, name: 'Algeria',          name_ko: '알제리',                 country_code: 'DZA', appearances: 4,  titles: [],                         runner_ups: [] },
  { id: 403, name: 'Tunisia',          name_ko: '튀니지',                 country_code: 'TUN', appearances: 6,  titles: [],                         runner_ups: [] },
  { id: 404, name: 'Egypt',            name_ko: '이집트',                 country_code: 'EGY', appearances: 3,  titles: [],                         runner_ups: [] },
  { id: 405, name: 'Senegal',          name_ko: '세네갈',                 country_code: 'SEN', appearances: 3,  titles: [],                         runner_ups: [] },
  { id: 406, name: 'Cameroon',         name_ko: '카메룬',                 country_code: 'CAM', appearances: 8,  titles: [],                         runner_ups: [] },
  { id: 407, name: 'Nigeria',          name_ko: '나이지리아',             country_code: 'NIG', appearances: 6,  titles: [],                         runner_ups: [] },
  { id: 408, name: 'Ghana',            name_ko: '가나',                   country_code: 'GHA', appearances: 4,  titles: [],                         runner_ups: [] },
  { id: 409, name: 'Ivory Coast',      name_ko: '코트디부아르',           country_code: 'CIV', appearances: 3,  titles: [],                         runner_ups: [] },
  { id: 410, name: 'South Africa',     name_ko: '남아프리카공화국',       country_code: 'RSA', appearances: 3,  titles: [],                         runner_ups: [] },
  { id: 411, name: 'Angola',           name_ko: '앙골라',                 country_code: 'ANG', appearances: 1,  titles: [],                         runner_ups: [] },
  { id: 412, name: 'Togo',             name_ko: '토고',                   country_code: 'TOG', appearances: 1,  titles: [],                         runner_ups: [] },
  { id: 414, name: 'DR Congo',         name_ko: '콩고민주공화국',         country_code: 'COD', appearances: 1,  titles: [],                         runner_ups: [] },
  { id: 415, name: 'Mali',             name_ko: '말리',                   country_code: 'MLI', appearances: 0,  titles: [],                         runner_ups: [] },
  { id: 416, name: 'Guinea',           name_ko: '기니',                   country_code: 'GIN', appearances: 0,  titles: [],                         runner_ups: [] },
  { id: 417, name: 'Burkina Faso',     name_ko: '부르키나파소',           country_code: 'BFA', appearances: 0,  titles: [],                         runner_ups: [] },
  { id: 418, name: 'Ethiopia',         name_ko: '에티오피아',             country_code: 'ETH', appearances: 0,  titles: [],                         runner_ups: [] },
  { id: 419, name: 'Kenya',            name_ko: '케냐',                   country_code: 'KEN', appearances: 0,  titles: [],                         runner_ups: [] },
  { id: 420, name: 'Mozambique',       name_ko: '모잠비크',               country_code: 'MOZ', appearances: 0,  titles: [],                         runner_ups: [] },
  { id: 421, name: 'Zambia',           name_ko: '잠비아',                 country_code: 'ZAM', appearances: 0,  titles: [],                         runner_ups: [] },
  { id: 422, name: 'Zimbabwe',         name_ko: '짐바브웨',               country_code: 'ZIM', appearances: 0,  titles: [],                         runner_ups: [] },
  { id: 423, name: 'Namibia',          name_ko: '나미비아',               country_code: 'NAM', appearances: 0,  titles: [],                         runner_ups: [] },

  // ── 아시아/중동 (500번대) ─────────────────────────────────────────
  { id: 501, name: 'South Korea',      name_ko: '대한민국',               country_code: 'KOR', appearances: 11, titles: [],                         runner_ups: [] },
  { id: 502, name: 'Japan',            name_ko: '일본',                   country_code: 'JPN', appearances: 7,  titles: [],                         runner_ups: [] },
  { id: 503, name: 'China',            name_ko: '중국',                   country_code: 'CHN', appearances: 1,  titles: [],                         runner_ups: [] },
  { id: 504, name: 'Iran',             name_ko: '이란',                   country_code: 'IRI', appearances: 6,  titles: [],                         runner_ups: [] },
  { id: 505, name: 'Saudi Arabia',     name_ko: '사우디아라비아',         country_code: 'KSA', appearances: 6,  titles: [],                         runner_ups: [] },
  { id: 506, name: 'Iraq',             name_ko: '이라크',                 country_code: 'IRA', appearances: 1,  titles: [],                         runner_ups: [] },
  { id: 507, name: 'Kuwait',           name_ko: '쿠웨이트',               country_code: 'KUW', appearances: 1,  titles: [],                         runner_ups: [] },
  { id: 508, name: 'UAE',              name_ko: '아랍에미리트',           country_code: 'UAE', appearances: 1,  titles: [],                         runner_ups: [] },
  { id: 509, name: 'Qatar',            name_ko: '카타르',                 country_code: 'QAT', appearances: 1,  titles: [],                         runner_ups: [] },
  { id: 510, name: 'Israel',           name_ko: '이스라엘',               country_code: 'ISR', appearances: 1,  titles: [],                         runner_ups: [] },
  { id: 511, name: 'North Korea',      name_ko: '북한',                   country_code: 'DPR', appearances: 2,  titles: [],                         runner_ups: [] },
  { id: 512, name: 'Kazakhstan',       name_ko: '카자흐스탄',             country_code: 'KAZ', appearances: 0,  titles: [],                         runner_ups: [] },
  { id: 513, name: 'Uzbekistan',       name_ko: '우즈베키스탄',           country_code: 'UZB', appearances: 0,  titles: [],                         runner_ups: [] },

  // ── 오세아니아 (600번대) ──────────────────────────────────────────
  { id: 601, name: 'Australia',        name_ko: '호주',                   country_code: 'AUS', appearances: 6,  titles: [],                         runner_ups: [] },
  { id: 602, name: 'New Zealand',      name_ko: '뉴질랜드',               country_code: 'NZL', appearances: 2,  titles: [],                         runner_ups: [] },
]