export { default as Home } from './home/Home'
export { default as Players } from './players/Players'
export { default as Teams } from './teams/Teams'
export { default as Records } from './records/Records'
export { default as History } from './history/History'
export { default as Games } from './games/Games'
export { default as Stats } from './stats/Stats'